<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastReport.OpenSource" Version="2026.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Repositorio\Repositorio.csproj" />
    <ProjectReference Include="..\Servicios\Servicios.csproj" />
    <ProjectReference Include="..\Dominio\Dominio.csproj" />
  </ItemGroup>

</Project>